# Generated by Django 2.2.4 on 2019-08-07 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cargo', models.CharField(max_length=30)),
                ('descricao_cargo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id_vaga', models.AutoField(primary_key=True, serialize=False)),
                ('nome_vaga', models.CharField(max_length=30)),
                ('descricao_vaga', models.TextField()),
                ('salario', models.FloatField()),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=30)),
                ('curriculo', models.FileField(upload_to='curriculos/')),
                ('idVaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vaga')),
            ],
        ),
    ]
