# Generated by Django 2.2.4 on 2019-08-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190807_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.CharField(max_length=10),
        ),
    ]
